In [1]:
import tensorflow as tf
print(tf.__version__)

1.3.0


In [ ]:
#declare vaiables | this is called building a computational graph

In [21]:
hello = tf.constant("Hello")

In [22]:
world = tf.constant("World")

In [ ]:
# 2 ways to handle tf sessions

In [26]:
#1st way: create a session and run that session
sess = tf.Session() #create session

In [24]:
print(sess.run(hello)) #run the session

b'Hello'


In [25]:
#2nd way: open the session with "with" 
with tf.Session() as sess:
    print(sess.run(hello))
    

b'Hello'


In [27]:
#go for it

In [28]:
a = tf.constant(1)
b = tf.constant(2)

In [35]:
with tf.Session() as sess:
    print(sess.run(a+b))

3


In [2]:
const = tf.constant(10)

In [3]:
fill_mat = tf.fill((4,4),10)

In [14]:
myzeros = tf.zeros((4,4))

In [5]:
myones = tf.ones((4,4))

In [16]:
myrandn = tf.random_normal((4,4))

In [17]:
myrandu = tf.random_uniform((4,4),maxval=1)

In [18]:
myops = [const,fill_mat,myzeros,myones,myrandn,myrandu]

In [19]:
sess = tf.InteractiveSession()

In [20]:
for op in myops:
    print(sess.run(op))
    print("\n")

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


[[ 0.28091797  1.06890631  0.79507518  1.29060018]
 [ 0.94806492 -0.65610504  1.16946912 -1.57941127]
 [ 0.13246328  0.82478982 -1.06163299  1.90069616]
 [ 0.30389664  1.39239156 -0.4958398  -0.35704982]]


[[ 0.86365843  0.50823009  0.0517168   0.59760487]
 [ 0.92300737  0.43488705  0.38751936  0.19495916]
 [ 0.14813972  0.98163474  0.64294088  0.52229095]
 [ 0.02131844  0.08186007  0.9794203   0.12498057]]


